//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentType
    {
        public ContentType()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int ContentType_Id { get; set; }
        public System.DateTime ContentType_Date { get; set; }
        public string ContentType_Description { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
