//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemSubjects = new HashSet<ItemSubject>();
            this.ItemTargets = new HashSet<ItemTarget>();
            this.Carts = new HashSet<Cart>();
        }
    
        public int Item_Id { get; set; }
        public System.DateTime Item_Date { get; set; }
        public string Item_Name { get; set; }
        public string Item_Description { get; set; }
        public string Item_TagWords { get; set; }
        public string Item_FilePath { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int ContentType_Id { get; set; }
        public int Phase_Id { get; set; }
        public string Item_SystemFileName { get; set; }
    
        public virtual ContentType ContentType { get; set; }
        public virtual Phase Phase { get; set; }
        public virtual ICollection<ItemSubject> ItemSubjects { get; set; }
        public virtual ICollection<ItemTarget> ItemTargets { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
    }
}
