//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBox.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KnowledgeBoxEntities : DbContext
    {
        public KnowledgeBoxEntities()
            : base("name=KnowledgeBoxEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ContentType> ContentTypes { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<ItemSubject> ItemSubjects { get; set; }
        public DbSet<ItemTarget> ItemTargets { get; set; }
        public DbSet<Phase> Phases { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<Target> Targets { get; set; }
    }
}
