//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBox.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Phase
    {
        public Phase()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int Phase_Id { get; set; }
        [DisplayName("Description")]
        public string Phase_Description { get; set; }
        public System.DateTime Phase_Date { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
