//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBox.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Subject
    {
        public Subject()
        {
            this.ItemSubjects = new HashSet<ItemSubject>();
        }
    
        public int Subject_Id { get; set; }
        [DisplayName("Description")]
        public string Subject_Description { get; set; }
        public System.DateTime Subject_Date { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<ItemSubject> ItemSubjects { get; set; }
    }
}
