//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeBox.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Target
    {
        public Target()
        {
            this.ItemTargets = new HashSet<ItemTarget>();
        }
    
        public int Target_Id { get; set; }
        [DisplayName("Description")]
        public string Target_Description { get; set; }
        public System.DateTime Target_Date { get; set; }
        public int CreatedBy { get; set; }
    
        public virtual ICollection<ItemTarget> ItemTargets { get; set; }
    }
}
